# Air Configuration for Hot Reload

# Root directory (change if needed)
root = "."
tmp_dir = "build"

# Build settings
[build]
  bin = "build/main.exe"
  cmd = "go build -o build/main.exe ./cmd/main.go"
  delay = 1000  
  exclude_dir = ["vendor", "build", "migrate"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_ext = ["md"]

# Log settings
[log]
  level = "debug"
